package tests;

import org.json.simple.JSONObject;
import org.testng.annotations.Test;

import io.restassured.http.ContentType;

import static io.restassured.RestAssured.*;


public class TestOnLocalAPI {
	
	
//	1. Install node js 
//  2. Go to command prompt and npm install -g json-server
//  3. Open File Explorer 
//  4. Create a folder C:\Users\<Your-name>\json-server-demo
//  5. Inside this folder, create a file called db.json
//  6. Open db.json in a text editor (VS Code / Notepad) and paste this:
	/*
	 * { "posts": [ { "id": 1, "title": "Hello World", "author": "Abarna" } ],
	 * "users": [ { "id": 1, "name": "Raghav" } ] }
	 */
//  7. Open CMD
//  8. Navigate to your folder:
//  9. json-server --watch db.json
//  10. If everything is correct, you will see something like:
	/*
	 * \{^_^}/ hi!
	 * 
	 * Loading db.json Done
	 * 
	 * Resources :
	 * http://localhost:3000/posts 
	 * http://localhost:3000/users
	 * 
	 * 
	 * Home http://localhost:3000
	 */
//  11. Open browser: http://localhost:3000
//  12. You should see the text inside the db.json file

//  12. 




	
	//@Test
	public void get() {
		baseURI = "http://localhost:3000";
		given().get("/posts").then().statusCode(200).log().all();
		
		
	}
	
	//@Test
	public void post() {
		
		JSONObject request = new JSONObject();
		request.put("title","Love Story");
		request.put("author","Abharnas"); // everytime id will be autogenerated 
		
		baseURI = "http://localhost:3000";
		given()
		.header("Content-Type","application-json")
		.contentType(ContentType.JSON)
		.accept(ContentType.JSON)
		.body(request.toJSONString())
		
		.when()
		   .post("/posts")
		.then()
		    .statusCode(201)
		    .log().all();
		
			
	}
	
	//@Test
	public void put() {
		JSONObject request = new JSONObject();
		request.put("title","Love Story forever");
		request.put("author","Abharnas");  
		
		baseURI = "http://localhost:3000";
		given()
		.header("Content-Type","application-json")
		.contentType(ContentType.JSON)
		.accept(ContentType.JSON)
		.body(request.toJSONString())
		
		.when()
		   .put("/posts/4215")
		.then()
		    .statusCode(200)
		    .log().all();
		
	}
	
	@Test
	public void patch() {
		JSONObject request = new JSONObject();
		//request.put("title","Love Story forever");
		request.put("author","Absharu");
		baseURI = "http://localhost:3000";
		given()
		.header("Content-Type","application-json")
		.contentType(ContentType.JSON)
		.accept(ContentType.JSON)
		.body(request.toJSONString())
		
		.when()
		   .patch("/posts/4215")
		.then()
		    .statusCode(200)
		    .log().all();
		
	}

}
